package jetbrains.mps.core.structure.pluginSolution.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import jetbrains.mps.project.IModule;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import jetbrains.mps.smodel.Language;
import org.jetbrains.annotations.NotNull;
import com.intellij.openapi.actionSystem.PlatformDataKeys;
import jetbrains.mps.ide.actions.MPSCommonDataKeys;
import jetbrains.mps.ide.messages.MessagesViewTool;
import com.intellij.openapi.project.Project;
import jetbrains.mps.messages.IMessageHandler;
import jetbrains.mps.messages.IMessage;
import jetbrains.mps.messages.Message;
import jetbrains.mps.messages.MessageKind;
import jetbrains.mps.smodel.MPSModuleRepository;
import jetbrains.mps.smodel.SModelFqName;
import jetbrains.mps.smodel.SModelDescriptor;
import jetbrains.mps.smodel.SModelRepository;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.DefaultSModelDescriptor;
import jetbrains.mps.core.util.merge.MergeSession;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.project.SModelRoot;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.smodel.persistence.DefaultModelRootManager;

public class MigrateStructure_Action extends BaseAction {
  private static final Icon ICON = null;
  protected static Log log = LogFactory.getLog(MigrateStructure_Action.class);

  public MigrateStructure_Action() {
    super("Migrate structure", "", ICON);
    this.setIsAlwaysVisible(false);
    this.setExecuteOutsideCommand(false);
  }

  @Override
  public boolean isDumbAware() {
    return true;
  }

  public boolean isApplicable(AnActionEvent event, final Map<String, Object> _params) {
    return ((IModule) MapSequence.fromMap(_params).get("module")) instanceof Language;
  }

  public void doUpdate(@NotNull AnActionEvent event, final Map<String, Object> _params) {
    try {
      {
        boolean enabled = this.isApplicable(event, _params);
        this.setEnabledState(event.getPresentation(), enabled);
      }
    } catch (Throwable t) {
      if (log.isErrorEnabled()) {
        log.error("User's action doUpdate method failed. Action:" + "MigrateStructure", t);
      }
      this.disable(event.getPresentation());
    }
  }

  protected boolean collectActionData(AnActionEvent event, final Map<String, Object> _params) {
    if (!(super.collectActionData(event, _params))) {
      return false;
    }
    MapSequence.fromMap(_params).put("project", event.getData(PlatformDataKeys.PROJECT));
    MapSequence.fromMap(_params).put("module", event.getData(MPSCommonDataKeys.MODULE));
    if (MapSequence.fromMap(_params).get("module") == null) {
      return false;
    }
    return true;
  }

  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    try {
      final MessagesViewTool tool = ((Project) MapSequence.fromMap(_params).get("project")).getComponent(MessagesViewTool.class);
      if (tool == null) {
        if (log.isErrorEnabled()) {
          log.error("cannot get message view tool");
        }
      }
      IMessageHandler mh = new IMessageHandler() {
        public void handle(IMessage p0) {
          tool.add(p0, "Migrate structure");
        }

        public void clear() {
          tool.clear("Migrate structure");
        }
      };
      Language language = (Language) ((IModule) MapSequence.fromMap(_params).get("module"));
      mh.handle(new Message(MessageKind.INFORMATION, "converting " + language.getModuleFqName()));

      Language newStructureLanguage = (Language) MPSModuleRepository.getInstance().getModuleByFqName("jetbrains.mps.core.structure");
      language.addUsedLanguage(newStructureLanguage.getModuleReference());
      SModelFqName newModelName = SModelFqName.fromString(language.getModuleFqName() + ".core");
      SModelDescriptor desc = SModelRepository.getInstance().getModelDescriptor(newModelName);
      SModel newStructure;
      SNode converted = new LanguageConverter(language, mh).convert();
      if (desc instanceof DefaultSModelDescriptor) {
        MergeSession session = new MergeSession(mh);
        session.replace((DefaultSModelDescriptor) desc, Sequence.<SNode>singleton(converted));
        session.restoreRefs();
        session.apply();
      } else {
        SModelRoot root = Sequence.fromIterable(((Iterable<SModelRoot>) language.getSModelRoots())).where(new IWhereFilter<SModelRoot>() {
          public boolean accept(SModelRoot it) {
            return it.getManager() instanceof DefaultModelRootManager;
          }
        }).first();
        newStructure = language.createModel(newModelName, root, null).getSModel();
        newStructure.addLanguage(newStructureLanguage.getModuleReference());
        newStructure.addRoot(converted);
      }
    } catch (Throwable t) {
      if (log.isErrorEnabled()) {
        log.error("User's action execute method failed. Action:" + "MigrateStructure", t);
      }
    }
  }
}
