package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */


public class SAllNotationsSelector_BehaviorDescriptor extends SNotationSelector_BehaviorDescriptor {
  public SAllNotationsSelector_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.notation.structure.SAllNotationsSelector";
  }
}
