package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */


public class SAllTermsSelector_BehaviorDescriptor extends SNotationTermSelector_BehaviorDescriptor {
  public SAllTermsSelector_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.notation.structure.SAllTermsSelector";
  }
}
