package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */


public class SConceptNotationSelector_BehaviorDescriptor extends SNotationSelector_BehaviorDescriptor {
  public SConceptNotationSelector_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.notation.structure.SConceptNotationSelector";
  }
}
