package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class SNotationSelector_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public SNotationSelector_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.notation.structure.SNotationSelector";
  }
}
