package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */


public class SNotationBreak_BehaviorDescriptor extends SNotationPart_BehaviorDescriptor {
  public SNotationBreak_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.notation.structure.SNotationBreak";
  }
}
