package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public interface SNotationWrapper_BehaviorDescriptor {
  public boolean virtual_hasSuffix_8379004527113948621(SNode thisNode);
  public boolean virtual_hasPrefix_8379004527113948625(SNode thisNode);
  public int virtual_getPrio_2711998566963954000(SNode thisNode);
}
