package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */

import jetbrains.mps.core.structure.behavior.SStructurePart_BehaviorDescriptor;
import jetbrains.mps.core.notation.util.NotationContext;
import jetbrains.mps.smodel.SNode;

public class SNotation_BehaviorDescriptor extends SStructurePart_BehaviorDescriptor implements SNotationPartsContainer_BehaviorDescriptor, SNotationContextProvider_BehaviorDescriptor {
  public SNotation_BehaviorDescriptor() {
  }

  public NotationContext virtual_getContext_8632884680339357870(SNode thisNode) {
    return SNotation_Behavior.virtual_getContext_8632884680339357870(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.notation.structure.SNotation";
  }
}
