package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;

public class SNotationStyleContent_BehaviorDescriptor extends SNotationStylePart_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor {
  public SNotationStyleContent_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.notation.structure.SNotationStyleContent";
  }
}
