package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class SNotationQuantifier_BehaviorDescriptor extends SNotationPart_BehaviorDescriptor implements SNotationWrapper_BehaviorDescriptor, SNotationPartWithStyle_BehaviorDescriptor {
  public SNotationQuantifier_BehaviorDescriptor() {
  }

  public boolean virtual_hasSuffix_8379004527113948621(SNode thisNode) {
    return SNotationQuantifier_Behavior.virtual_hasSuffix_8379004527113948621(thisNode);
  }

  public boolean virtual_hasPrefix_8379004527113948625(SNode thisNode) {
    return SNotationQuantifier_Behavior.virtual_hasPrefix_8379004527113948625(thisNode);
  }

  public int virtual_getPrio_2711998566963954000(SNode thisNode) {
    return SNotationQuantifier_Behavior.virtual_getPrio_2711998566963954000(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.notation.structure.SNotationQuantifier";
  }
}
