package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class SNotationNewLine_BehaviorDescriptor extends SNotationViewPart_BehaviorDescriptor {
  public SNotationNewLine_BehaviorDescriptor() {
  }

  public boolean virtual_hasNewLineAfter_3647933405694801735(SNode thisNode) {
    return SNotationNewLine_Behavior.virtual_hasNewLineAfter_3647933405694801735(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.notation.structure.SNotationNewLine";
  }
}
