package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */


public abstract class SNotationViewPart_BehaviorDescriptor extends SNotationPart_BehaviorDescriptor {
  public SNotationViewPart_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.notation.structure.SNotationViewPart";
  }
}
