package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */


public abstract class SNotationTextualPart_BehaviorDescriptor extends SNotationPart_BehaviorDescriptor {
  public SNotationTextualPart_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.notation.structure.SNotationTextualPart";
  }
}
