package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.notation.util.NotationContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class SNotationPart_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean virtual_hasNewLineAfter_3647933405694801735(SNode thisNode) {
    return false;
  }

  public static boolean virtual_hasNewLineBefore_3647933405694801750(SNode thisNode) {
    return false;
  }

  public static NotationContext virtual_getContext_8632884680339357870(SNode thisNode) {
    if (SNodeOperations.isInstanceOf(SNodeOperations.getParent(thisNode), "jetbrains.mps.core.notation.structure.SNotationContextProvider")) {
      return BehaviorReflection.invokeVirtual(NotationContext.class, SNodeOperations.cast(SNodeOperations.getParent(thisNode), "jetbrains.mps.core.notation.structure.SNotationContextProvider"), "virtual_getContext_8632884680339357870", new Object[]{});
    }
    return null;
  }

  public static boolean call_inMultilineContext_7465902928068905821(SNode thisNode) {
    SNode parent = SNodeOperations.as(SNodeOperations.getParent(thisNode), "jetbrains.mps.core.notation.structure.SNotationPartList");
    return parent != null && SNotationPartList_Behavior.call_isMultiline_7465902928068862404(parent);
  }

  @Deprecated
  public static boolean call_hasNewLineAfter_3647933405694801735(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(Boolean.TYPE, thisNode, "virtual_hasNewLineAfter_3647933405694801735", new Object[]{});
  }

  @Deprecated
  public static boolean call_hasNewLineBefore_3647933405694801750(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(Boolean.TYPE, thisNode, "virtual_hasNewLineBefore_3647933405694801750", new Object[]{});
  }

  @Deprecated
  public static boolean callSuper_hasNewLineAfter_3647933405694801735(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(Boolean.TYPE, SNodeOperations.cast(thisNode, "jetbrains.mps.core.notation.structure.SNotationPart"), callerConceptFqName, "virtual_hasNewLineAfter_3647933405694801735", new Class[]{SNode.class}, new Object[]{});
  }

  @Deprecated
  public static boolean callSuper_hasNewLineBefore_3647933405694801750(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(Boolean.TYPE, SNodeOperations.cast(thisNode, "jetbrains.mps.core.notation.structure.SNotationPart"), callerConceptFqName, "virtual_hasNewLineBefore_3647933405694801750", new Class[]{SNode.class}, new Object[]{});
  }
}
