package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class SNotationQuantifier_Behavior {
  public static void init(SNode thisNode) {
  }
}
