package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.notation.util.NotationContext;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class SNotationMapping_Behavior {
  public static void init(SNode thisNode) {
  }

  public static NotationContext virtual_getContext_8632884680339357870(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(NotationContext.class, SLinkOperations.getTarget(thisNode, "entityRef", true), "virtual_getContext_8632884680339377253", new Object[]{});
  }
}
