package jetbrains.mps.core.notation.behavior;

/*Generated by MPS */

import jetbrains.mps.core.notation.util.NotationContext;
import jetbrains.mps.smodel.SNode;

public class SStructurePropertyRef_BehaviorDescriptor extends SStructureEntityRef_BehaviorDescriptor {
  public SStructurePropertyRef_BehaviorDescriptor() {
  }

  public NotationContext virtual_getContext_8632884680339377253(SNode thisNode) {
    return SStructurePropertyRef_Behavior.virtual_getContext_8632884680339377253(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.notation.structure.SStructurePropertyRef";
  }
}
