package jetbrains.mps.core.smodel.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.nodeEditor.CellActionType;
import jetbrains.mps.nodeEditor.EditorCellAction;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class SConceptQuery_deleteAbstract {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.DELETE, new SConceptQuery_deleteAbstract.SConceptQuery_deleteAbstract_DELETE(node));
  }

  public static class SConceptQuery_deleteAbstract_DELETE extends EditorCellAction {
    /*package*/ SNode myNode;

    public SConceptQuery_deleteAbstract_DELETE(SNode node) {
      this.myNode = node;
    }

    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }

    public void execute_internal(EditorContext editorContext, SNode node) {
      SPropertyOperations.set(node, "isAbstract", "" + (false));
    }
  }
}
