package jetbrains.mps.core.query.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MqlComma extends MqlBinaryExpr implements MqlScopeProvider {
  public static final String concept = "jetbrains.mps.core.query.structure.MqlComma";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public MqlComma(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(MqlComma.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(MqlComma.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(MqlComma.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(MqlComma.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(MqlComma.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(MqlComma.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(MqlComma.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, MqlComma.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, MqlComma.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(MqlComma.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, MqlComma.SMODEL_ATTRIBUTE, node);
  }

  public static MqlComma newInstance(SModel sm, boolean init) {
    return (MqlComma) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.core.query.structure.MqlComma", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MqlComma newInstance(SModel sm) {
    return MqlComma.newInstance(sm, false);
  }
}
