package jetbrains.mps.core.query.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MqlIntType extends MqlType {
  public static final String concept = "jetbrains.mps.core.query.structure.MqlIntType";

  public MqlIntType(SNode node) {
    super(node);
  }

  public static MqlIntType newInstance(SModel sm, boolean init) {
    return (MqlIntType) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.core.query.structure.MqlIntType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MqlIntType newInstance(SModel sm) {
    return MqlIntType.newInstance(sm, false);
  }
}
