package jetbrains.mps.core.query.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.structure.structure.AbstractConceptDeclaration;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MqlNodeType extends MqlType {
  public static final String concept = "jetbrains.mps.core.query.structure.MqlNodeType";
  public static final String CONCEPT = "concept";

  public MqlNodeType(SNode node) {
    super(node);
  }

  public AbstractConceptDeclaration getConcept() {
    return (AbstractConceptDeclaration) this.getReferent(AbstractConceptDeclaration.class, MqlNodeType.CONCEPT);
  }

  public void setConcept(AbstractConceptDeclaration node) {
    super.setReferent(MqlNodeType.CONCEPT, node);
  }

  public static MqlNodeType newInstance(SModel sm, boolean init) {
    return (MqlNodeType) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.core.query.structure.MqlNodeType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MqlNodeType newInstance(SModel sm) {
    return MqlNodeType.newInstance(sm, false);
  }
}
