package jetbrains.mps.core.query.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MqlParameterReference extends MqlExpression {
  public static final String concept = "jetbrains.mps.core.query.structure.MqlParameterReference";
  public static final String PARAMETER = "parameter";

  public MqlParameterReference(SNode node) {
    super(node);
  }

  public MqlParameter getParameter() {
    return (MqlParameter) this.getReferent(MqlParameter.class, MqlParameterReference.PARAMETER);
  }

  public void setParameter(MqlParameter node) {
    super.setReferent(MqlParameterReference.PARAMETER, node);
  }

  public static MqlParameterReference newInstance(SModel sm, boolean init) {
    return (MqlParameterReference) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.core.query.structure.MqlParameterReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MqlParameterReference newInstance(SModel sm) {
    return MqlParameterReference.newInstance(sm, false);
  }
}
