package jetbrains.mps.core.query.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MqlSelector extends BaseConcept {
  public static final String concept = "jetbrains.mps.core.query.structure.MqlSelector";

  public MqlSelector(SNode node) {
    super(node);
  }

  public static MqlSelector newInstance(SModel sm, boolean init) {
    return (MqlSelector) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.core.query.structure.MqlSelector", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MqlSelector newInstance(SModel sm) {
    return MqlSelector.newInstance(sm, false);
  }
}
