package jetbrains.mps.core.query.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum MqlSubstringKind {
  charAt("charAt", 1),
  substring("substring", 2);

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return "" + this.myValue;
  }

  public static List<MqlSubstringKind> getConstants() {
    List<MqlSubstringKind> list = ListSequence.fromList(new LinkedList<MqlSubstringKind>());
    ListSequence.fromList(list).addElement(MqlSubstringKind.charAt);
    ListSequence.fromList(list).addElement(MqlSubstringKind.substring);
    return list;
  }

  public static MqlSubstringKind getDefault() {
    return null;
  }

  public static MqlSubstringKind parseValue(String value) {
    if (value == null) {
      return MqlSubstringKind.getDefault();
    }
    if (value.equals(MqlSubstringKind.charAt.getValueAsString())) {
      return MqlSubstringKind.charAt;
    }
    if (value.equals(MqlSubstringKind.substring.getValueAsString())) {
      return MqlSubstringKind.substring;
    }
    return MqlSubstringKind.getDefault();
  }

  private int myValue;

  MqlSubstringKind(String name, int value) {
    this.myName = name;
    this.myValue = value;
  }

  public int getValue() {
    return this.myValue;
  }
}
