package jetbrains.mps.core.query.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MqlVariableReference extends MqlExpression {
  public static final String concept = "jetbrains.mps.core.query.structure.MqlVariableReference";
  public static final String VAR = "var";

  public MqlVariableReference(SNode node) {
    super(node);
  }

  public MqlVariable getVar() {
    return (MqlVariable) this.getReferent(MqlVariable.class, MqlVariableReference.VAR);
  }

  public void setVar(MqlVariable node) {
    super.setReferent(MqlVariableReference.VAR, node);
  }

  public static MqlVariableReference newInstance(SModel sm, boolean init) {
    return (MqlVariableReference) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.core.query.structure.MqlVariableReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MqlVariableReference newInstance(SModel sm) {
    return MqlVariableReference.newInstance(sm, false);
  }
}
