package jetbrains.mps.core.structure.findUsages;

/*Generated by MPS */

import jetbrains.mps.ide.findusages.BaseFindUsagesDescriptor;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;

public class FindUsagesDescriptor extends BaseFindUsagesDescriptor {
  public FindUsagesDescriptor() {
    super(PersistenceFacade.getInstance().createModuleReference("1372eb94-b402-4b9f-bb3f-44315b20f92d(jetbrains.mps.core.structure)"), PersistenceFacade.getInstance().createModelReference("r:ba11a22c-8766-40f4-811f-3748286e3c92(jetbrains.mps.core.structure.findUsages)"));
  }

  public void init() {
    add(new ConceptInheritors_Finder(), "5130788244153403834");
  }
}
