package jetbrains.mps.core.syntax.java.structure;

/*Generated by MPS */

import jetbrains.mps.core.syntax.structure.SAction;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.baseLanguage.structure.Statement;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SJavaAction extends SAction {
  public static final String concept = "jetbrains.mps.core.syntax.java.structure.SJavaAction";
  public static final String STATEMENTS = "statements";

  public SJavaAction(SNode node) {
    super(node);
  }

  public int getStatementsesCount() {
    return this.getChildCount(SJavaAction.STATEMENTS);
  }

  public Iterator<Statement> statementses() {
    return this.children(Statement.class, SJavaAction.STATEMENTS);
  }

  public List<Statement> getStatementses() {
    return this.getChildren(Statement.class, SJavaAction.STATEMENTS);
  }

  public void addStatements(Statement node) {
    this.addChild(SJavaAction.STATEMENTS, node);
  }

  public void insertStatements(Statement prev, Statement node) {
    this.insertChild(prev, SJavaAction.STATEMENTS, node);
  }

  public static SJavaAction newInstance(SModel sm, boolean init) {
    return (SJavaAction) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.core.syntax.java.structure.SJavaAction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SJavaAction newInstance(SModel sm) {
    return SJavaAction.newInstance(sm, false);
  }
}
