package jetbrains.mps.core.syntax.java.structure;

/*Generated by MPS */

import jetbrains.mps.core.syntax.structure.SAction;
import jetbrains.mps.baseLanguage.structure.ILocalVariableElementList;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.baseLanguage.structure.Statement;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SJavaAction extends SAction implements ILocalVariableElementList {
  public static final String concept = "jetbrains.mps.core.syntax.java.structure.SJavaAction";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String STATEMENTS = "statements";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public SJavaAction(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(SJavaAction.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(SJavaAction.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(SJavaAction.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(SJavaAction.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(SJavaAction.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(SJavaAction.VIRTUAL_PACKAGE, value);
  }

  public int getStatementsesCount() {
    return this.getChildCount(SJavaAction.STATEMENTS);
  }

  public Iterator<Statement> statementses() {
    return this.children(Statement.class, SJavaAction.STATEMENTS);
  }

  public List<Statement> getStatementses() {
    return this.getChildren(Statement.class, SJavaAction.STATEMENTS);
  }

  public void addStatements(Statement node) {
    this.addChild(SJavaAction.STATEMENTS, node);
  }

  public void insertStatements(Statement prev, Statement node) {
    this.insertChild(prev, SJavaAction.STATEMENTS, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(SJavaAction.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, SJavaAction.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, SJavaAction.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(SJavaAction.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, SJavaAction.SMODEL_ATTRIBUTE, node);
  }

  public static SJavaAction newInstance(SModel sm, boolean init) {
    return (SJavaAction) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.core.syntax.java.structure.SJavaAction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SJavaAction newInstance(SModel sm) {
    return SJavaAction.newInstance(sm, false);
  }
}
