package jetbrains.mps.core.syntax.java.behavior;

/*Generated by MPS */

import jetbrains.mps.core.syntax.behavior.SType_BehaviorDescriptor;

public class SJavaType_BehaviorDescriptor extends SType_BehaviorDescriptor {
  public SJavaType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.syntax.java.structure.SJavaType";
  }
}
