package jetbrains.mps.query.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MqlBoolType extends MqlType {
  public static final String concept = "jetbrains.mps.query.structure.MqlBoolType";

  public MqlBoolType(SNode node) {
    super(node);
  }

  public static MqlBoolType newInstance(SModel sm, boolean init) {
    return (MqlBoolType) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.query.structure.MqlBoolType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MqlBoolType newInstance(SModel sm) {
    return MqlBoolType.newInstance(sm, false);
  }
}
