package jetbrains.mps.query.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MqlCollectionSelectorVarRef extends MqlExpression {
  public static final String concept = "jetbrains.mps.query.structure.MqlCollectionSelectorVarRef";
  public static final String VAR = "var";

  public MqlCollectionSelectorVarRef(SNode node) {
    super(node);
  }

  public MqlCollectionSelectorVar getVar() {
    return (MqlCollectionSelectorVar) this.getReferent(MqlCollectionSelectorVar.class, MqlCollectionSelectorVarRef.VAR);
  }

  public void setVar(MqlCollectionSelectorVar node) {
    super.setReferent(MqlCollectionSelectorVarRef.VAR, node);
  }

  public static MqlCollectionSelectorVarRef newInstance(SModel sm, boolean init) {
    return (MqlCollectionSelectorVarRef) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.query.structure.MqlCollectionSelectorVarRef", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MqlCollectionSelectorVarRef newInstance(SModel sm) {
    return MqlCollectionSelectorVarRef.newInstance(sm, false);
  }
}
