package jetbrains.mps.query.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MqlParentheses extends MqlExpression {
  public static final String concept = "jetbrains.mps.query.structure.MqlParentheses";
  public static final String EXPR = "expr";

  public MqlParentheses(SNode node) {
    super(node);
  }

  public MqlExpression getExpr() {
    return (MqlExpression) this.getChild(MqlExpression.class, MqlParentheses.EXPR);
  }

  public void setExpr(MqlExpression node) {
    super.setChild(MqlParentheses.EXPR, node);
  }

  public static MqlParentheses newInstance(SModel sm, boolean init) {
    return (MqlParentheses) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.query.structure.MqlParentheses", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MqlParentheses newInstance(SModel sm) {
    return MqlParentheses.newInstance(sm, false);
  }
}
