package jetbrains.mps.query.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface MqlVariableContainer extends INodeAdapter {
  public static final String concept = "jetbrains.mps.query.structure.MqlVariableContainer";
}
