package jetbrains.mps.core.structure.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public abstract class SAbstractConcept_BehaviorDescriptor extends SStructureElement_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public SAbstractConcept_BehaviorDescriptor() {
  }

  public boolean virtual_isSubConceptOf_5938997310819191538(SNode thisNode, SNode concept) {
    return SAbstractConcept_Behavior.virtual_isSubConceptOf_5938997310819191538(thisNode, concept);
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.structure.structure.SAbstractConcept";
  }
}
