package jetbrains.mps.core.structure.behavior;

/*Generated by MPS */


public class SChildLink_BehaviorDescriptor extends SAbstractLink_BehaviorDescriptor {
  public SChildLink_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.structure.structure.SChildLink";
  }
}
