package jetbrains.mps.core.structure.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class SConceptMember_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode call_getContainingConcept_4125821269968947769(SNode thisNode) {
    return SNodeOperations.as(SNodeOperations.getParent(thisNode), "jetbrains.mps.core.structure.structure.SAbstractConcept");
  }
}
