package jetbrains.mps.core.structure.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class SConstraints_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean call_isMultiline_2223786200032678198(SNode thisNode) {
    return ListSequence.fromList(SLinkOperations.getTargets(thisNode, "parts", true)).any(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return BehaviorReflection.invokeVirtual(Boolean.TYPE, it, "virtual_isMultiline_2223786200032678188", new Object[]{});
      }
    });
  }
}
