package jetbrains.mps.core.structure.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;

public class SProperty_BehaviorDescriptor extends SConceptFeature_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor {
  public SProperty_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.structure.structure.SProperty";
  }
}
