package jetbrains.mps.core.structure.behavior;

/*Generated by MPS */


public class SStructureEmptyLine_BehaviorDescriptor extends SStructureElement_BehaviorDescriptor {
  public SStructureEmptyLine_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.structure.structure.SStructureEmptyLine";
  }
}
