package jetbrains.mps.core.syntax.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class SNonTerm_Constraints extends BaseConstraintsDescriptor {
  public SNonTerm_Constraints() {
    super("jetbrains.mps.core.syntax.structure.SNonTerm");
  }
}
