package jetbrains.mps.core.syntax.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"jetbrains.mps.core.syntax.structure.SGrammarPart", "jetbrains.mps.core.syntax.structure.SInputRef", "jetbrains.mps.core.syntax.structure.SLexem", "jetbrains.mps.core.syntax.structure.SLexerPart", "jetbrains.mps.core.syntax.structure.SLineComment", "jetbrains.mps.core.syntax.structure.SNamedPattern", "jetbrains.mps.core.syntax.structure.SNonTerm", "jetbrains.mps.core.syntax.structure.SPrio", "jetbrains.mps.core.syntax.structure.SReference", "jetbrains.mps.core.syntax.structure.SRegex", "jetbrains.mps.core.syntax.structure.SRule", "jetbrains.mps.core.syntax.structure.SSource", "jetbrains.mps.core.syntax.structure.SSymbol", "jetbrains.mps.core.syntax.structure.SSymbolRef"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 11:
        return new SSource_BehaviorDescriptor();
      case 2:
        return new SLexem_BehaviorDescriptor();
      case 12:
        return new SSymbol_BehaviorDescriptor();
      case 10:
        return new SRule_BehaviorDescriptor();
      case 6:
        return new SNonTerm_BehaviorDescriptor();
      case 13:
        return new SSymbolRef_BehaviorDescriptor();
      case 9:
        return new SRegex_BehaviorDescriptor();
      case 5:
        return new SNamedPattern_BehaviorDescriptor();
      case 7:
        return new SPrio_BehaviorDescriptor();
      case 8:
        return new SReference_BehaviorDescriptor();
      case 1:
        return new SInputRef_BehaviorDescriptor();
      case 3:
        return new SLexerPart_BehaviorDescriptor();
      case 4:
        return new SLineComment_BehaviorDescriptor();
      case 0:
        return new SGrammarPart_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
