package jetbrains.mps.core.syntax.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class SAction_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean virtual_isSingleLine_5989029785192054872(SNode thisNode) {
    return false;
  }

  @Deprecated
  public static boolean call_isSingleLine_5989029785192054872(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(Boolean.TYPE, thisNode, "virtual_isSingleLine_5989029785192054872", new Object[]{});
  }

  @Deprecated
  public static boolean callSuper_isSingleLine_5989029785192054872(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(Boolean.TYPE, SNodeOperations.cast(thisNode, "jetbrains.mps.core.syntax.structure.SAction"), callerConceptFqName, "virtual_isSingleLine_5989029785192054872", new Class[]{SNode.class}, new Object[]{});
  }
}
