package jetbrains.mps.core.syntax.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public abstract class SAction_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements SRulePart_BehaviorDescriptor {
  public SAction_BehaviorDescriptor() {
  }

  public boolean virtual_isSingleLine_5989029785192054872(SNode thisNode) {
    return SAction_Behavior.virtual_isSingleLine_5989029785192054872(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.syntax.structure.SAction";
  }
}
