package jetbrains.mps.core.syntax.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;

public class SLexem_BehaviorDescriptor extends SLexerPart_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor {
  public SLexem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.syntax.structure.SLexem";
  }
}
