package jetbrains.mps.core.syntax.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;

public class SNonTerm_BehaviorDescriptor extends SGrammarPart_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor {
  public SNonTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.syntax.structure.SNonTerm";
  }
}
