package jetbrains.mps.core.template.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import jetbrains.mps.core.query.behavior.MqlParametersContainer_BehaviorDescriptor;

public interface MtlEntity_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor, MqlParametersContainer_BehaviorDescriptor {
}
