package jetbrains.mps.core.template.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.LinkAttribute_BehaviorDescriptor;

public class MtlReferenceMacro_BehaviorDescriptor extends LinkAttribute_BehaviorDescriptor {
  public MtlReferenceMacro_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.template.structure.MtlReferenceMacro";
  }
}
