package jetbrains.mps.core.template.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.scope.SimpleRoleScope;

public class MtlTemplate_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode call_getTemplateRoot_3373821274546492156(SNode thisNode) {
    List<SNode> rootMarkers = SNodeOperations.getDescendants(SLinkOperations.getTarget(thisNode, "template", true), "jetbrains.mps.core.template.structure.MtlTemplateRoot", false, new String[]{});
    if ((int) ListSequence.fromList(rootMarkers).count() == 1) {
      SNode node = ListSequence.fromList(rootMarkers).first();
      return SNodeOperations.getParent(node);
    }
    return SLinkOperations.getTarget(thisNode, "template", true);
  }

  public static Scope virtual_getScope_3734116213129936182(SNode thisNode, SNode kind, SNode child) {
    if (kind == SConceptOperations.findConceptDeclaration("jetbrains.mps.core.query.structure.MqlParameter")) {
      return SimpleRoleScope.forNamedElements(thisNode, SLinkOperations.findLinkDeclaration("jetbrains.mps.core.query.structure.MqlParametersContainer", "parameters"));
    }
    return null;
  }
}
