package jetbrains.mps.query.behavior;

/*Generated by MPS */


public class MqlBoolLiteral_BehaviorDescriptor extends MqlExpression_BehaviorDescriptor {
  public MqlBoolLiteral_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.query.structure.MqlBoolLiteral";
  }
}
