package jetbrains.mps.query.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class MqlClosure_BehaviorDescriptor extends MqlExpression_BehaviorDescriptor implements MqlParametersContainer_BehaviorDescriptor {
  public MqlClosure_BehaviorDescriptor() {
  }

  public SNode virtual_getType_228266671027861783(SNode thisNode) {
    return MqlClosure_Behavior.virtual_getType_228266671027861783(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.query.structure.MqlClosure";
  }
}
