package jetbrains.mps.query.behavior;

/*Generated by MPS */


public class MqlLinkSelector_BehaviorDescriptor extends MqlSelector_BehaviorDescriptor {
  public MqlLinkSelector_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.query.structure.MqlLinkSelector";
  }
}
