package jetbrains.mps.query.behavior;

/*Generated by MPS */


public class MqlListType_BehaviorDescriptor extends MqlType_BehaviorDescriptor {
  public MqlListType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.query.structure.MqlListType";
  }
}
