package jetbrains.mps.query.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class MqlNullLiteral_BehaviorDescriptor extends MqlExpression_BehaviorDescriptor {
  public MqlNullLiteral_BehaviorDescriptor() {
  }

  public SNode virtual_getType_228266671027861783(SNode thisNode) {
    return MqlNullLiteral_Behavior.virtual_getType_228266671027861783(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.query.structure.MqlNullLiteral";
  }
}
