package jetbrains.mps.query.behavior;

/*Generated by MPS */


public class MqlParentheses_BehaviorDescriptor extends MqlExpression_BehaviorDescriptor {
  public MqlParentheses_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.query.structure.MqlParentheses";
  }
}
