package jetbrains.mps.query.behavior;

/*Generated by MPS */


public class MqlStringType_BehaviorDescriptor extends MqlType_BehaviorDescriptor {
  public MqlStringType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.query.structure.MqlStringType";
  }
}
