package jetbrains.mps.query.behavior;

/*Generated by MPS */


public class MqlTriplex_BehaviorDescriptor extends MqlExpression_BehaviorDescriptor {
  public MqlTriplex_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.query.structure.MqlTriplex";
  }
}
