package jetbrains.mps.query.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.query.runtime.EvaluationEnvironment;
import jetbrains.mps.query.runtime.EvaluationContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class MqlVariableReference_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Object virtual_evaluate_1671449901154581105(SNode thisNode, EvaluationEnvironment env, EvaluationContext context) {
    return MqlExpression_Behavior.callSuper_evaluate_1671449901154581105(thisNode, "jetbrains.mps.query.structure.MqlVariableReference", env, context);
  }

  public static SNode virtual_getType_228266671027861783(SNode thisNode) {
    if ((SLinkOperations.getTarget(thisNode, "var", false) != null)) {
      return MqlVariable_Behavior.call_getType_3435983127247055576(SLinkOperations.getTarget(thisNode, "var", false));
    }
    return null;
  }
}
