package jetbrains.mps.query.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class MqlVarReference_BehaviorDescriptor extends MqlExpression_BehaviorDescriptor {
  public MqlVarReference_BehaviorDescriptor() {
  }

  public SNode virtual_getType_228266671027861783(SNode thisNode) {
    return MqlVarReference_Behavior.virtual_getType_228266671027861783(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.query.structure.MqlVarReference";
  }
}
