package jetbrains.mps.core.notation.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;

public class goodEnterHandling {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.INSERT, new goodEnterHandling.goodEnterHandling_INSERT(node));
  }

  public static class goodEnterHandling_INSERT extends AbstractCellAction {
    /*package*/ SNode myNode;

    public goodEnterHandling_INSERT(SNode node) {
      this.myNode = node;
    }

    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }

    public void execute_internal(EditorContext editorContext, SNode node) {
      if (ListSequence.fromList(SLinkOperations.getTargets(node, "alternatives", true)).isEmpty()) {
        SNodeFactoryOperations.addNewChild(node, "alternatives", "jetbrains.mps.core.notation.structure.SNotationPartList");
      } else {
        SNodeFactoryOperations.addNewChild(ListSequence.fromList(SLinkOperations.getTargets(node, "alternatives", true)).last(), "parts", "jetbrains.mps.core.notation.structure.SNotationBreak");
      }
    }
  }
}
