package jetbrains.mps.core.query.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class MqlListType_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean virtual_isSubtypeOf_2852142168179579064(SNode thisNode, SNode type) {
    if (SNodeOperations.isInstanceOf(type, "jetbrains.mps.core.query.structure.MqlListType")) {
      return MqlType_Behavior.call_isSubtypeOf_2852142168179579064(SLinkOperations.getTarget(thisNode, "inner", true), SLinkOperations.getTarget(SNodeOperations.cast(type, "jetbrains.mps.core.query.structure.MqlListType"), "inner", true));
    }
    return false;
  }

  public static String virtual_getSignature_270269450479785729(SNode thisNode) {
    return "list<>";
  }

  public static String virtual_getText_270269450479797040(SNode thisNode) {
    return "list<" + MqlType_Behavior.call_getText_270269450479797040(SLinkOperations.getTarget(thisNode, "inner", true)) + ">";
  }
}
