package jetbrains.mps.core.query.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import jetbrains.mps.core.query.runtime.QueryScope;
import jetbrains.mps.smodel.SNode;

public interface MqlScopeExporter_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
  public QueryScope virtual_getExportedScope_5109194352282852190(SNode thisNode);
}
