package jetbrains.mps.core.query.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class MqlType_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean virtual_isSubtypeOf_2852142168179579064(SNode thisNode, SNode type) {
    return false;
  }

  public static String virtual_getSignature_270269450479785729(SNode thisNode) {
    return null;
  }

  public static String virtual_getText_270269450479797040(SNode thisNode) {
    return MqlType_Behavior.call_getSignature_270269450479785729(thisNode);
  }

  @Deprecated
  public static boolean call_isSubtypeOf_2852142168179579064(SNode thisNode, SNode type) {
    return BehaviorReflection.invokeVirtual(Boolean.TYPE, thisNode, "virtual_isSubtypeOf_2852142168179579064", new Object[]{type});
  }

  @Deprecated
  public static String call_getSignature_270269450479785729(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(String.class, thisNode, "virtual_getSignature_270269450479785729", new Object[]{});
  }

  @Deprecated
  public static String call_getText_270269450479797040(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(String.class, thisNode, "virtual_getText_270269450479797040", new Object[]{});
  }

  @Deprecated
  public static boolean callSuper_isSubtypeOf_2852142168179579064(SNode thisNode, String callerConceptFqName, SNode type) {
    return BehaviorManager.getInstance().invokeSuper(Boolean.TYPE, SNodeOperations.cast(thisNode, "jetbrains.mps.core.query.structure.MqlType"), callerConceptFqName, "virtual_isSubtypeOf_2852142168179579064", new Class[]{SNode.class, SNode.class}, new Object[]{type});
  }

  @Deprecated
  public static String callSuper_getSignature_270269450479785729(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(String.class, SNodeOperations.cast(thisNode, "jetbrains.mps.core.query.structure.MqlType"), callerConceptFqName, "virtual_getSignature_270269450479785729", new Class[]{SNode.class}, new Object[]{});
  }

  @Deprecated
  public static String callSuper_getText_270269450479797040(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(String.class, SNodeOperations.cast(thisNode, "jetbrains.mps.core.query.structure.MqlType"), callerConceptFqName, "virtual_getText_270269450479797040", new Class[]{SNode.class}, new Object[]{});
  }
}
