package jetbrains.mps.core.query.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface MqlThisProvider_BehaviorDescriptor {
  public SNode virtual_getThisType_4125821269968916020(SNode thisNode);
}
