package jetbrains.mps.core.metadata.behavior;

/*Generated by MPS */


public class SConceptAnnotationMemberEmptyLine_BehaviorDescriptor extends SConceptAnnotationMember_BehaviorDescriptor {
  public SConceptAnnotationMemberEmptyLine_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.metadata.structure.SConceptAnnotationMemberEmptyLine";
  }
}
