package jetbrains.mps.core.metadata.behavior;

/*Generated by MPS */

import jetbrains.mps.core.query.behavior.MqlExpression_BehaviorDescriptor;

public class SMetadataNodeRefExpression_BehaviorDescriptor extends MqlExpression_BehaviorDescriptor {
  public SMetadataNodeRefExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.metadata.structure.SMetadataNodeRefExpression";
  }
}
