package jetbrains.mps.core.smodel.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class removeAbstract_QuickFix extends QuickFix_Runtime {
  public removeAbstract_QuickFix() {
  }

  public String getDescription(SNode node) {
    return "Make non-abstract";
  }

  public void execute(SNode node) {
    SPropertyOperations.set(SNodeOperations.cast(node, "jetbrains.mps.core.smodel.structure.SConceptQuery"), "isAbstract", "" + false);
  }
}
