package jetbrains.mps.query.runtime;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class EvaluationException extends RuntimeException {
  private SNode query;
  private EvaluationContext context;

  public EvaluationException(String message, SNode query, EvaluationContext context) {
    super(message);
    this.query = query;
    this.context = context;
  }

  public SNode getQuery() {
    return query;
  }

  public EvaluationContext getContext() {
    return context;
  }
}
