package jetbrains.mps.template.behavior;

/*Generated by MPS */


public class MtlForeachMacro_BehaviorDescriptor extends MtlNodeMacro_BehaviorDescriptor {
  public MtlForeachMacro_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.template.structure.MtlForeachMacro";
  }
}
