package jetbrains.mps.template.behavior;

/*Generated by MPS */


public class MtlNodeQueryMacro_BehaviorDescriptor extends MtlNodeMacro_BehaviorDescriptor {
  public MtlNodeQueryMacro_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.template.structure.MtlNodeQueryMacro";
  }
}
