package jetbrains.mps.template.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.NodeAttribute_BehaviorDescriptor;

public class MtlTemplateRoot_BehaviorDescriptor extends NodeAttribute_BehaviorDescriptor {
  public MtlTemplateRoot_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.template.structure.MtlTemplateRoot";
  }
}
