package jetbrains.mps.core.smodel.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.util.Set;
import java.util.HashSet;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MqlPropertySelector_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_getType_228266671027867010(SNode thisNode) {
    SNode dt = SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "property", false), "type", true);
    if (SNodeOperations.isInstanceOf(dt, "jetbrains.mps.core.structure.structure.SPrimitiveDataType")) {
      SNode pdt = SNodeOperations.cast(dt, "jetbrains.mps.core.structure.structure.SPrimitiveDataType");
      if (SPropertyOperations.hasValue(pdt, "kind", "string", "string")) {
        return new MqlPropertySelector_Behavior.QuotationClass_wadyfu_a0a0b0b0b().createNode();
      } else if (SPropertyOperations.hasValue(pdt, "kind", "int", "string")) {
        return new MqlPropertySelector_Behavior.QuotationClass_wadyfu_a0a0a1a1a1().createNode();
      } else if (SPropertyOperations.hasValue(pdt, "kind", "bool", "string")) {
        return new MqlPropertySelector_Behavior.QuotationClass_wadyfu_a0a0b1a1a1().createNode();
      }
    }
    return null;
  }

  public static class QuotationClass_wadyfu_a0a0b0b0b {
    public QuotationClass_wadyfu_a0a0b0b0b() {
    }

    public SNode createNode() {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.core.query.structure.MqlStringType", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_2 = quotedNode_1;
        result = quotedNode1_2;
      }
      return result;
    }
  }

  public static class QuotationClass_wadyfu_a0a0a1a1a1 {
    public QuotationClass_wadyfu_a0a0a1a1a1() {
    }

    public SNode createNode() {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.core.query.structure.MqlIntType", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_2 = quotedNode_1;
        result = quotedNode1_2;
      }
      return result;
    }
  }

  public static class QuotationClass_wadyfu_a0a0b1a1a1 {
    public QuotationClass_wadyfu_a0a0b1a1a1() {
    }

    public SNode createNode() {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.core.query.structure.MqlBoolType", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_2 = quotedNode_1;
        result = quotedNode1_2;
      }
      return result;
    }
  }
}
