package jetbrains.mps.core.smodel.behavior;

/*Generated by MPS */

import jetbrains.mps.core.query.behavior.MqlSelector_BehaviorDescriptor;

public class SConceptQueryCall_BehaviorDescriptor extends MqlSelector_BehaviorDescriptor {
  public SConceptQueryCall_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.smodel.structure.SConceptQueryCall";
  }
}
