package jetbrains.mps.core.smodel.behavior;

/*Generated by MPS */

import jetbrains.mps.core.query.behavior.MqlExpression_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class SEnumLiteralRef_BehaviorDescriptor extends MqlExpression_BehaviorDescriptor {
  public SEnumLiteralRef_BehaviorDescriptor() {
  }

  public SNode virtual_getType_228266671027861783(SNode thisNode) {
    return SEnumLiteralRef_Behavior.virtual_getType_228266671027861783(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.core.smodel.structure.SEnumLiteralRef";
  }
}
